### ISSUE TITLE
No check on xerolinux database

### ISSUE THREAD

**Issue by IllanRULDACUNHA** [xerolinux/xlapit-cli#2]
Hello,

I just noticed that each time I launch the script, it adds the xerolinux database to the /etc/pacman.conf, causing a `database already registered` error when I try to update my packages with paru (or yay).

![image](https://github.com/xerolinux/xlapit-cli/assets/26620176/daeb51e0-fda9-4b46-a178-d094a4f7061b)

A check should be added before adding this XeroLinux section to the pacman.conf file. Thanks a lot!

**Comment by DarkXero-dev** [comment]
You do not need to re-run curl command every time you want to run the toolkit. It's there in your Appmenu or you can run it via the `xero-cli -m` terminal command. Might clarify that on the site.

**Comment by DKMellow** [comment]
Hey Dark, 

sorry for reopening the issues but a friend of mine that also uses linux and he recently installed xero using the script and had the same issue since he ran the scipt multiple times using the curl command. 

I know this is not the proper way to run the script as you said but it would still be nice to have a check in case someone else runs it again like this since its not made that clear, so a fix would be appreciated ;D

**Comment by DarkXero-dev** [comment]
No problem. I will figure out a way if there is one. For now will just add in on readme not to run curl command multiple times...

**Comment by DKMellow** [comment]
Appreciate it!

**Comment by DarkXero-dev** [comment]
@DKMellow Done ! Readme updated .. Will figure it out soon..
