### ISSUE TITLE
Didn't detect all linux kernels

### ISSUE THREAD

**Issue by nt74** [xerolinux/xlapit-cli#5]
I used Your Toolkit for an MSI laptop that I decided to run on the ZEN-kernel.
It couldn't finish the GPU installation without errors because it didn't detect and install all needed kernel-headers.
A suggestion from me would be to detect what kernels are currently installed and give the user the choice which kernel(s) to install headers for (?)
Otherwise a great tool and now my laptop works great with fully functioning sleep/hibernate and audio. Hybrid cards are known to be a real challenge to make work and Your script did a great job at that!

All the best,
Nikos

**Comment by DarkXero-dev** [comment]
Hello @nt74 

Thanks for the useful suggestion, but since I do not provide custom Kernels, nor will I any time soon leaving it up to you the user to know that with every Kernel you must install headers, part of the learning curve. 

This tool was and always will be intended for Vanilla Arch, thus expecting you to have some amount of knowledge. Not meant as spoon feeding tool. (Please don't mind the analogy).

That's why it will always install default Kernel's headers, leaving custom ones up to you. If I did everything for you then you will end up learning nothing having to always rely on me. 

I hope that clarifies things. Again thanks.

**Comment by DarkXero-dev** [comment]
@nt74 

Now that is a better idea. I will add it to the readme here on Github. Adding to toolkit will not work since message disappears too quickly for users to see it. If they do not read the readme it's their issue not mine. (I don't mean to sound bad just an observation that users ignore what's written a lot).
